SELECT A.ANIMAL_ID, A.NAME

FROM(

    SELECT  A.ANIMAL_ID, A.NAME, (B.DATETIME - A.DATETIME) AS DATETIME
    FROM ANIMAL_INS A
    INNER JOIN ANIMAL_OUTS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
    ORDER BY DATETIME DESC
    ) A
    
WHERE ROWNUM <=2;
