--각 회원은 한번씩 카운트 되어야 하기 때문에 DISTINCT로 중복을 제거
SELECT TO_CHAR(B.SALES_DATE, 'YYYY') AS YEAR, TO_NUMBER(TO_CHAR(B.SALES_DATE, 'MM')) AS MONTH, A.GENDER, COUNT(DISTINCT A.USER_ID) AS USERS
FROM USER_INFO A 
JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID

WHERE GENDER IS NOT NULL
GROUP BY TO_CHAR(B.SALES_DATE, 'YYYY'), TO_CHAR(B.SALES_DATE, 'MM'), GENDER
ORDER BY 1, 2, 3