-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME ,GENDER ,TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL
-- 생일이 3월인 사람 (달만 TO_CHAR 해주면 됨)
AND TO_CHAR(DATE_OF_BIRTH, 'MM') = 3
AND GENDER ='W'
ORDER BY MEMBER_ID;