--SELECT DATETIME AS 시간
--FROM ANIMAL_INS
--WHERE DATETIME = (SELECT MIN(DATETIME)
--                  FROM ANIMAL_INS);
                  
-- 코드를 입력하세요
SELECT DATETIME 시간
FROM (
    SELECT ANIMAL_TYPE, DATETIME
    FROM ANIMAL_INS
    ORDER BY DATETIME
    )
WHERE ROWNUM = 1;
